### ISSUE TITLE
Queue pagination

### ISSUE THREAD

**Issue by NotSoMik** [fisherboneee/Rabbito#1]
![Screenshot_20220409-001313_Discord](https://user-images.githubusercontent.com/74645196/162539859-97604458-3399-4182-b57b-cc2635c34a04.jpg)
About the queue command, if there are more than like 5 songs the bot must add buttons on the message, can you add this feature :)

**Comment by fisherboneee** [comment]
Hello!
Sure, I'm planning on making this in the future update, so stay tuned!

_thanks for the suggestion tho <3_
